// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import { Turbo } from "@hotwired/turbo-rails";

// Start Turbo
Turbo.start();

// Import and register Stimulus controllers
import { definitionsFromContext } from "@hotwired/stimulus-webpack-helpers";
const context = require.context("./", true, /\.js$/);
application.load(definitionsFromContext(context));
